version: 2
registries:
  npm-registry-npm-pkg-github-com-platformbuilders:
    type: npm-registry
    url: https://npm.pkg.github.com/platformbuilders
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_PLATFORMBUILDERS_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Brazil/East
  open-pull-requests-limit: 10
  reviewers:
  - digitals
  labels:
  - dependencies
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.46
    - 0.63.48
    - 0.63.49
    - 0.63.50
    - 0.63.51
    - 0.64.0
    - 0.64.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
    - 0.30.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.0.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 3.10.1
  registries:
  - npm-registry-npm-pkg-github-com-platformbuilders
