version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'monthly'
    target_branch: 'master'

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - 'digitals'
    default_labels:
      - 'dependencies'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:minor'
